spring.application.name=portal
# This enables the visual database console
spring.h2.console.enabled=true
# This sets the address of the database so we can find it
spring.datasource.url=jdbc:h2:mem:testdb
# This makes sure the console is accessible
spring.h2.console.path=/h2-console

#GMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chatagapata03@gmail.com
spring.mail.password=oecamygmmqdrpags
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
