spring.application.name=portal
# This enables the visual database console
spring.h2.console.enabled=true
# This sets the address of the database so we can find it
spring.datasource.url=jdbc:h2:mem:testdb
# This makes sure the console is accessible
spring.h2.console.path=/h2-console
